RESPONSES = {
    "hello": "Hey there! 😊 How can I help you today?",
    "hi": "Hi! It's nice to see you. What can I do for you?",
    "hey": "Hey! Hope you're having a great day.",
    "how are you": "I'm doing well, thanks for asking! How about you?",
    "what are you doing": "Just chatting with you and waiting for your next question!",
    "what's up": "Not much, just here to help. What's up with you?",
    "i am fine": "That's great to hear! 😊",
    "i am good": "Awesome! Keep smiling.",
    "i am happy": "That makes me happy too! 🎉",
    "i am sad": "I'm sorry you're feeling that way. Tomorrow is a new day.",
    "who are you": "I'm your friendly AI assistant. I'm here to chat and help.",
    "what is your name": "You can call me AI Assistant.",
    "where do you live": "I live inside this application and in the world of code. 😄",
    "can you help me": "Of course! Tell me what you need help with.",
    "thank you": "You're very welcome! 😊",
    "thanks": "Anytime! Happy to help.",
    "good job": "Thank you! That means a lot.",
    "you are smart": "That's kind of you to say!",
    "tell me a joke": "Why don't programmers like nature? It has too many bugs! 😄",
    "another joke": "Why did the computer get cold? Because it left its Windows open!",
    "make me laugh": "I would tell you a UDP joke, but you might not get it. 😆",
    "i am bored": "Maybe try learning a new skill, watching a tech video, or building a small project.",
    "motivate me": "Every expert was once a beginner. Keep going, you're improving every day!",
    "inspire me": "Success comes from consistency, not perfection.",
    "good morning": "Good morning! 🌞 Wishing you a productive day.",
    "good afternoon": "Good afternoon! Hope your day is going well.",
    "good evening": "Good evening! Ready to learn something new?",
    "good night": "Good night! 🌙 Rest well and recharge.",
    "do you like me": "Of course! I enjoy our conversations.",
    "are you my friend": "Absolutely! I'm always here to chat with you.",
    "can we be friends": "Definitely! Friends help each other learn and grow.",
    "what can you do": "I can answer questions, chat with you, and help you learn new things.",
    "are you real": "I'm a virtual assistant, but our conversation is real!",
    "are you human": "Nope, I'm an AI assistant created with code.",
    "i love coding": "That's awesome! Coding opens up so many opportunities.",
    "i want a job": "Keep learning, build projects, and stay consistent. You'll get there!",
    "i want to learn python": "Great choice! Python is beginner-friendly and very powerful.",
    "bye": "Goodbye! 👋 Have a wonderful day.",
    "see you later": "See you later! Take care.",
    "what is python": "Python is a high-level programming language known for its simplicity and versatility.",
    "what is java": "Java is an object-oriented programming language widely used for enterprise applications.",
    "what is c": "C is a powerful programming language often used for system programming.",
    "what is c++": "C++ is an extension of C that supports object-oriented programming.",
    "what is javascript": "JavaScript is used to make web pages interactive and dynamic.",
    "what is html": "HTML stands for HyperText Markup Language and is used to structure web pages.",
    "what is css": "CSS stands for Cascading Style Sheets and is used to style web pages.",
    "what is react": "React is a JavaScript library for building user interfaces.",
    "what is node js": "Node.js allows JavaScript to run on the server side.",
    "what is flask": "Flask is a lightweight Python framework used for web development.",
    "what is django": "Django is a powerful Python framework for building web applications.",
    "what is api": "An API allows different software applications to communicate with each other.",
    "what is github": "GitHub is a platform for hosting and managing code repositories.",
    "what is git": "Git is a version control system used to track code changes.",
    "what is sql": "SQL is used to store, retrieve, and manage data in databases.",
    "what is mysql": "MySQL is a popular relational database management system.",
    "what is mongodb": "MongoDB is a NoSQL database that stores data in JSON-like documents.",
    "what is ai": "Artificial Intelligence enables machines to perform tasks that typically require human intelligence.",
    "what is machine learning": "Machine Learning is a branch of AI where systems learn from data.",
    "what is deep learning": "Deep Learning uses neural networks to solve complex problems.",
    "what is data science": "Data Science combines statistics, programming, and analytics to extract insights from data.",
    "what is cloud computing": "Cloud Computing provides computing resources over the internet.",
    "what is aws": "AWS is Amazon's cloud computing platform.",
    "what is cybersecurity": "Cybersecurity protects systems and networks from digital attacks.",
    "what is dsa": "DSA stands for Data Structures and Algorithms.",
    "why learn dsa": "DSA improves problem-solving skills and helps in coding interviews.",
    "what is a linked list": "A linked list is a linear data structure where elements are connected using pointers.",
    "what is a stack": "A stack follows the Last In First Out (LIFO) principle.",
    "what is a queue": "A queue follows the First In First Out (FIFO) principle.",
    "what is an array": "An array stores multiple elements of the same type in contiguous memory.",
    "what is oops": "OOPS stands for Object-Oriented Programming System and includes concepts like inheritance and polymorphism.",
    "what is inheritance": "Inheritance allows one class to acquire properties of another class.",
    "what is polymorphism": "Polymorphism allows methods to perform different tasks based on the object.",
    "what is encapsulation": "Encapsulation hides data and restricts direct access to it.",
    "what is abstraction": "Abstraction hides implementation details and shows only essential features.",
    "how to get placement": "Focus on DSA, projects, aptitude, communication skills, and mock interviews.",
    "what skills are needed for placements": "Communication, DSA, projects, problem-solving, and resume building.",
    "how to improve coding": "Practice coding daily on platforms like LeetCode and HackerRank.",
    "best website for coding practice": "LeetCode, HackerRank, CodeChef, and GeeksforGeeks are excellent choices.",
    "what is leetcode": "LeetCode is a platform for practicing coding interview questions.",
    "what is hackerrank": "HackerRank helps improve coding and problem-solving skills.",
    "what is a resume": "A resume highlights your education, skills, projects, and achievements.",
    "how many projects should i have": "Having 2-4 quality projects is usually sufficient for placements.",
    "what is a portfolio": "A portfolio website showcases your skills, projects, and achievements.",
    "how to crack interviews": "Practice coding, communication, aptitude, and mock interviews regularly.",
    "take care": "You too! Stay happy and keep learning."
}

FALLBACK_RESPONSES = [
    "That's an interesting question! I'm still learning new things.",
    "I'm not sure about that yet, but I'd love to learn more.",
    "Hmm, I don't have an answer for that right now.",
    "Could you ask that in a different way?",
    "I'm still improving. Try asking me something else!"
]
